### PR TITLE
automatic backup script folder downloading/updating

### PR DESCRIPTION
**Pull request by Rubberduckycooly**
added functionality to automatically manage the scripts/ folder since there were some people that had issues with downloading it manually, and telling everyone to download it again when I update then would be a huge pain that I'd rather avoid

### CODE REVIEW

**Comment by thesupersonic16** [comment]
Looks good to me, @MainMemory Can you also review this?

**Comment by MainMemory** [comment]
Uh oh, the build tool did not like that.
`  Program.cs(31,5): error CS0246: The type or namespace name 'Octokit' could not be found (are you missing a using dire
ctive or an assembly reference?) [D:\Programs\SCDSteamModLoader\SCDSteamModManager\SCDSteamModManager.csproj]
  Program.cs(31,39): error CS0246: The type or namespace name 'Octokit' could not be found (are you missing a using dir
ective or an assembly reference?) [D:\Programs\SCDSteamModLoader\SCDSteamModManager\SCDSteamModManager.csproj]
  Program.cs(31,64): error CS0246: The type or namespace name 'Octokit' could not be found (are you missing a using dir
ective or an assembly reference?) [D:\Programs\SCDSteamModLoader\SCDSteamModManager\SCDSteamModManager.csproj]`

**Comment by MainMemory** [comment]
Right, nuget.

**Comment by MainMemory** [comment]
All good now!

**Pull request merged**
